Section "Module"
    Load "fbdevhw"
    Load "vgahw"
    Load "int10"
    Load "exa"
    Load "shadow"
    Load "shadowfb"
EndSection

Section "Device"
    Identifier "Card0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "Card0"
EndSection
